# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb2c4b01563b9ca2f27d146c41ebb6bc3183ababeb1412254087802a0f937e0be76e92c67e4db340ed35b63b6bf26aebdb631a3f9fb6a4cc5a52fd1a0154a53

test:
  secret_key_base: 2b723c5fdc03562de742f63dab2806a1efb77e2a3be2ed99a4592e705711b2759b0d6a2e9b7419195cf33b6b8ccd7fffd0edc42589be71ab3c6f2530dd58c90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
